config/routes.rb
Messtechnik::Application.routes.draw do
  resources :devices

  get "static_pages/index"

  devise_for :users

  root :to => 'static_pages#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :brand, :calibration_date, :deflection, :description, :folio, :model, :next_calibration, :responsible, :user_id, :status

  validates_presence_of :brand, :calibration_date, :folio, :model, :next_calibration, :responsible, :status

  belongs_to :user

  def nok(user)
  	user.devices.where("status == ?", "NOK")
  end
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :device_type
  # attr_accessible :title, :body
  validates_presence_of :username

  has_many :devices, :dependent => :destroy

  def next_calibration
    device = []
    self.devices.each do |equipo|
      logger.debug "#{equipo}\n\n\n\n\n\n"
      if Time.now-30.days <= equipo.next_calibration && Time.now >= equipo.next_calibration
        device << equipo
        return device
      end
    end 
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  before_filter :authenticate_user!, except: [:index, :show]
  helper_method :sort_column, :sort_direction
  def index
    @search = Device.search(params[:search])
    @devices = @search.order(sort_column + " " + sort_direction)
  #  @devices = Device.
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
  def sort_column
    Device.column_names.include?(params[:sort]) ? params[:sort] : "folio"
  end
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	if user_signed_in?
  		@search = current_user.devices.search(params[:search])
    	@devices = @search.order(sort_column + " " + sort_direction)
    	@devices_nok = current_user.devices.where(status: "NOK")
      @devices_next = current_user.devices
      @devices_next = @devices_next.where('next_calibration > ?', Time.now-30.days)
      @devices_next = @devices_next.where('next_calibration < ?', Time.now)
      #@devices_next = current_user.devices.all(:conditions => ["next_calibration >= ?", Time.now-30.days])
  	end
  end

  private
  def sort_column
    Device.column_names.include?(params[:sort]) ? params[:sort] : "folio"
  end
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def next_calibration(user)
    device = []
    user.devices.each do |equipo|
      logger.debug "#{equipo}\n\n\n\n\n\n"
      if Time.now-30.days <= equipo.next_calibration && Time.now >= equipo.next_calibration
        device << equipo
        return device
      end
    end 
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction =  column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
<% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-md-12">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :folio %><br />
        <%= f.text_field :folio %>
      </div>
      <div class="form-group">
        <%= f.label :description, "Descripción" %><br />
        <%= f.text_field :description %>
      </div>
      <div class="form-group">
        <%= f.label :brand, "Marca" %><br />
        <%= f.text_field :brand %>
      </div>
      <div class="form-group">
        <%= f.label :model, "Modelo" %><br />
        <%= f.text_field :model %>
      </div>
   
      <div class="form-group">
        <%= f.label :calibration_date, "Fecha de última calibración" %><br />
        <%= f.date_select :calibration_date, :start_year => 2000, :end_year => 2020 %>
      </div>
      <div class="form-group">
        <%= f.label :next_calibration, "Fecha de próxima calibración" %><br />
        <%= f.date_select :next_calibration, :start_year => 2000, :end_year => 2020 %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :deflection, "Observaciones" %><br />
        <%= f.text_area :deflection, cols: "40", rows: "5" %>
      </div>
      <div class="form-group">
        <%= f.label :responsible, "Responsable" %><br />
        <%= f.select(:responsible, User.all.collect {|p| [ p.username, p.username ]}, 
         :prompt => "Please select") %>
      </div>
      <div class="form-group">
        <%= f.label :status, "Status del calibración" %><br/>
        <%= f.select(:status, [['OK', 'OK'],
                                      ['NOK', 'NOK'],
                                      ['Dañado', 'Dañado'],
                                      ['Hasta su uso', 'Hasta su uso']
                                     ],{ :prompt => "Please select"}) %>
      </div>
      <% if current_user.id == 1 %>
        <div class="field">
          <%= f.label :user_id %><br />
          <%= f.number_field :user_id %>
        </div>
      <% else %>
        <div style="display:none">
          <%= f.number_field :user_id, :value => "#{current_user.id}" %>
        </div>
      <% end %>
      <br>
      <br>
      <div class="col-md-4">
        <div class="actions">
          <%= f.submit class: "btn btn-success btn-lg" %>
        </div>
      </div>
      <div class="col-md-1">
        <%= link_to 'Cancelar', :back, class: "btn btn-danger btn-lg" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', :back %>

app/views/devices/index.html.erb
<div class="row">
    <div class="col-md-12">
    <h1>Listado de dispositivos</h1>
    <div class="row">
        <%= form_for @search do |f| %>
            <div class="col-md-2">
                    <%= f.text_field :folio_or_description_or_brand_or_model_or_deflection_or_responsible_or_status_contains, size: '27' %>
            </div>
            <div class="col-md-2">
                <%= f.submit "Buscar", class: "btn btn-default" %><br>
            </div>
        <% end %>
        <br>
    </div>
    <table class="table table-striped">
      <tr>
        <th><%= sortable "folio", "Inventario" %></th>
        <th><%= sortable "description", "Descripción" %></th>
        <th><%= sortable "brand", "Marca" %></th>
        <th><%= sortable "model", "Modelo" %></th>
        <th><%= sortable "calibration_date", "Última calibración" %></th>
        <th><%= sortable "next_calibration", "Próxima calibración" %></th>
        <th><%= sortable "deflection", "Observaciones" %></th>
        <th><%= sortable "responsible", "Responsable" %></th>
        <th><%= sortable "status", "Status" %></th>
     <% if current_user.id == 1 %>   
        <th>User</th>
     <% end %>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @devices.each do |device| %>
        <% case device.status %>
            <% when "OK" %>
              <tr class="success">
                <td><%= device.folio %></td>
                <td><%= device.description %></td>
                <td><%= device.brand %></td>
                <td><%= device.model %></td>
                <td><%= device.calibration_date %></td>
                <td><%= device.next_calibration %></td>
                <td><%= device.deflection %></td>
                <td><%= device.responsible %></td>
                <td><%= device.status %></td>
            <% if current_user.id == 1 %>   
                <td><%= device.user_id %></td>
            <% end %>
                <td><%= link_to 'Ver detalles', device %></td>
            <% if current_user.id == 1 || current_user.id == device.user_id %>
                <td><%= link_to 'Editar', edit_device_path(device) %></td>
                <td><%= link_to 'Borrar', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
              </tr>
            <% when "NOK" %>
              <tr class="danger">
                <td><%= device.folio %></td>
                <td><%= device.description %></td>
                <td><%= device.brand %></td>
                <td><%= device.model %></td>
                <td><%= device.calibration_date %></td>
                <td><%= device.next_calibration %></td>
                <td><%= device.deflection %></td>
                <td><%= device.responsible %></td>
                <td><%= device.status %></td>
            <% if current_user.id == 1 %>   
                <td><%= device.user_id %></td>
            <% end %>
                <td><%= link_to 'Ver detalles', device %></td>
            <% if current_user.id == 1 || current_user.id == device.user_id %>
                <td><%= link_to 'Editar', edit_device_path(device) %></td>
                <td><%= link_to 'Borrar', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
              </tr>
            <% when "Hasta su uso" %>
                <tr class="info">
                    <td><%= device.folio %></td>
                    <td><%= device.description %></td>
                    <td><%= device.brand %></td>
                    <td><%= device.model %></td>
                    <td><%= device.calibration_date %></td>
                    <td><%= device.next_calibration %></td>
                    <td><%= device.deflection %></td>
                    <td><%= device.responsible %></td>
                    <td><%= device.status %></td>
                <% if current_user.id == 1 %>   
                    <td><%= device.user_id %></td>
                <% end %>
                    <td><%= link_to 'Ver detalles', device %></td>
                <% if current_user.id == 1 || current_user.id == device.user_id %>
                    <td><%= link_to 'Editar', edit_device_path(device) %></td>
                    <td><%= link_to 'Borrar', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
                  </tr>
            <% else %>
                <tr>
                    <td><%= device.folio %></td>
                    <td><%= device.description %></td>
                    <td><%= device.brand %></td>
                    <td><%= device.model %></td>
                    <td><%= device.calibration_date %></td>
                    <td><%= device.next_calibration %></td>
                    <td><%= device.deflection %></td>
                    <td><%= device.responsible %></td>
                    <td><%= device.status %></td>
                <% if current_user.id == 1 %>   
                    <td><%= device.user_id %></td>
                <% end %>
                    <td><%= link_to 'Ver detalles', device %></td>
                <% if current_user.id == 1 || current_user.id == device.user_id %>
                    <td><%= link_to 'Editar', edit_device_path(device) %></td>
                    <td><%= link_to 'Borrar', device, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                <% end %>
                  </tr>
        <% end %>
    <% end %>
    </table>

    <br />

    <%= link_to 'Nuevo dispositvo', new_device_path, class: "btn btn-primary btn-lg" %>
    </div>
 </div>

app/views/devices/new.html.erb
<div class="container">
	<h1>Nuevo dispositivo</h1>
	<%= render 'form' %>
</div>

app/views/devices/show.html.erb
<div class="container"><p id="notice"><%= notice %></p>
  <div class="col-md-4">
    <p>
      <b>Folio:</b>
      <%= @device.folio %>
    </p>

    <p>
      <b>Descripción:</b>
      <%= @device.description %>
    </p>

    <p>
      <b>Marca:</b>
      <%= @device.brand %>
    </p>

    <p>
      <b>Modelo:</b>
      <%= @device.model %>
    </p>

    <p>
      <b>Fecha de última calibración:</b>
      <%= @device.calibration_date %>
    </p>

    <p>
      <b>Fecha de próxima calibración:</b>
      <%= @device.next_calibration %>
    </p>

    <p>
      <b>Observaciones:</b>
      <%= @device.deflection %>
    </p>

    <p>
      <b>Responsable:</b>
      <%= @device.responsible %>
    </p>

    <% case @device.status %>
      <% when "OK" %>
      <p class="bg-success">
        <b>Status de calibración:</b>
        <%= @device.status %>
      </p>
      <% when "NOK" %>
      <p class="bg-danger">
        <b>Status de calibración:</b>
        <%= @device.status %>
      </p>
      <% when "Dañado" %>
      <p class="bg-warning">
        <b>Status de calibración:</b>
        <%= @device.status %>
      </p>
      <% when "Hasta su uso" %>
      <p class="bg-info">
        <b>Status de calibración:</b>
        <%= @device.status %>
      </p>
      <% else %>
      <p>
        <b>Status de calibración:</b>
        <%= @device.status %>
      </p>
    <% end %>
    <% if current_user.id == 1 %>
      <p>
        <b>User:</b>
        <%= @device.user_id %>
      </p>
    <% end %>
    <% if current_user.id == @device.user_id || current_user.id == 1 %>
      <%= link_to 'Actualizar', edit_device_path(@device) %> |
    <% end %>
    <%= link_to 'Regresar', :back %>
  </div>
</div>

app/views/layouts/_footer.html.erb
	<div class="container">
		<footer>
			<p class="lead">Desarrollado por <%= link_to "@JulioAhuactzin", "https://twitter.com/JulioAhuactzin", target: "_blank"%></p>
		</footer>
	</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <%= link_to image_tag("logo.png", :border => 0, :alt => '', :title => ''), root_path, :class => 'navbar-brand', style: "width:18%" %>
  </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <%= render 'layouts/navigation_links' %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
		<li ><%= link_to 'Mis dispositivos', root_path %></li>
        <li ><%= link_to 'Inventario', devices_path %></li>
		<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sesion de <%= current_user.username %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
			<li><%= link_to 'Editar', edit_user_registration_path %> </li>
			<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
	<% else %>
		<li><%= link_to 'Regístrate', new_user_registration_path %></li>
		<li><%= link_to 'Iniciar Sesión', new_user_session_path %></li>
	<% end %>
</ul>

<script type="text/javascript">
$(document).ready(function(){
    $('.navbar .dropdown').hover(function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(150).slideDown();
    }, function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(100).slideUp()
    });
})

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Messtechnik" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Messtechnik" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/_table.html.erb
   <!-- <div class="row">
        <%= form_for @search do |f| %>
            <div class="col-md-2">
                    <%= f.text_field :folio_or_description_or_brand_or_model_or_deflection_or_responsible_or_status_contains, size: '27' %>
            </div>
            <div class="col-md-2">
                <%= f.submit "Buscar", class: "btn btn-default" %><br>
            </div>
        <% end %>
        <br>
    </div> -->
    <div class="row">
        <div class="col-md-6">
            <table class="table table-striped">
                <h3>Equipos fuera de calibración</h3>
                <tr>
                    <th>Inventario</th>
                    <th>Descripción</th>
                    <th>Status</th>
                    <th></th>
                    <th></th>
                </tr>
                <% @devices_nok.each do |device| %>
                    <tr class="danger">
                        <td><%= device.folio %></td>
                        <td><%= device.description %></td>
                        <td><%= device.status %></td>
                        <td><%= link_to "Ver detalles", device %></td>
                        <td><%= link_to 'Editar', edit_device_path(device) %></td>
                    </tr>
                <% end %>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table table-striped">
                <h3>Calibración por vencer</h3>
                 <tr>
                    <th>Inventario</th>
                    <th>Descripción</th>
                    <th>Próxima calibración</th>
                    <th>Status</th>
                </tr>
                <% @devices_next.each do |device| %>
                    <tr>
                        <td><%= device.folio %></td>
                        <td><%= device.description %></td>
                        <td><%= device.next_calibration %></td>
                        <td><%= device.status %></td>
                    </tr>
                <% end %>

            </table>
        </div>
    </div>
    <table class="table table-striped">
      <h3>Tus equipos asignados</h3>
      <tr>
        <th>Inventario</th>
        <th>Descripción</th>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Última calibración</th>
        <th>Próxima calibración</th>
        <th>Observaciones</th>
        <th>Responsable</th>
        <th>Status</th>
     <% if current_user.id == 1 %>   
        <th>User</th>
     <% end %>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @devices.each do |device| %>
        <% case device.status %>
            <% when "NOK" %>
              <tr class="danger">
                <td><%= device.folio %></td>
                <td><%= device.description %></td>
                <td><%= device.brand %></td>
                <td><%= device.model %></td>
                <td><%= device.calibration_date %></td>
                <td><%= device.next_calibration %></td>
                <td><%= device.deflection %></td>
                <td><%= device.responsible %></td>
                <td><%= device.status %></td>
            <% if current_user.id == 1 %>   
                <td><%= device.user_id %></td>
            <% end %>
                <td><%= link_to 'Ver detalles', device %></td>
                <td><%= link_to 'Editar', edit_device_path(device) %></td>
                <td><%= link_to 'Borrar', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% when "Hasta su uso" %>
                <tr class="info">
                    <td><%= device.folio %></td>
                    <td><%= device.description %></td>
                    <td><%= device.brand %></td>
                    <td><%= device.model %></td>
                    <td><%= device.calibration_date %></td>
                    <td><%= device.next_calibration %></td>
                    <td><%= device.deflection %></td>
                    <td><%= device.responsible %></td>
                    <td><%= device.status %></td>
                <% if current_user.id == 1 %>   
                    <td><%= device.user_id %></td>
                <% end %>
                    <td><%= link_to 'Ver detalles', device %></td>
                    <td><%= link_to 'Editar', edit_device_path(device) %></td>
                    <td><%= link_to 'Borrar', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
            <% when "OK" %>
                <tr class="success">
                    <td><%= device.folio %></td>
                    <td><%= device.description %></td>
                    <td><%= device.brand %></td>
                    <td><%= device.model %></td>
                    <td><%= device.calibration_date %></td>
                    <td><%= device.next_calibration %></td>
                    <td><%= device.deflection %></td>
                    <td><%= device.responsible %></td>
                    <td><%= device.status %></td>
                <% if current_user.id == 1 %>   
                    <td><%= device.user_id %></td>
                <% end %>
                    <td><%= link_to 'Ver detalles', device %></td>
                    <td><%= link_to 'Editar', edit_device_path(device) %></td>
                    <td><%= link_to 'Borrar', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
            <% else %>
                <tr>
                    <td><%= device.folio %></td>
                    <td><%= device.description %></td>
                    <td><%= device.brand %></td>
                    <td><%= device.model %></td>
                    <td><%= device.calibration_date %></td>
                    <td><%= device.next_calibration %></td>
                    <td><%= device.deflection %></td>
                    <td><%= device.responsible %></td>
                    <td><%= device.status %></td>
                <% if current_user.id == 1 %>   
                    <td><%= device.user_id %></td>
                <% end %>
                    <td><%= link_to 'Ver detalles', device %></td>
                    <td><%= link_to 'Editar', edit_device_path(device) %></td>
                    <td><%= link_to 'Borrar', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
        <% end %>
    <% end %>
    </table>

    <br />
    <div class="col-md-3">
        <%= link_to 'Ver inventario', devices_path, class: "btn btn-primary btn-lg" %>
    </div>
    <div class="col-md-3">
        <%= link_to 'Nuevo dispositvo', new_device_path, class: "btn btn-primary btn-lg" %>
    </div>

app/views/static_pages/index.html.erb
<% if user_signed_in? %>
	<div class="row">
		<div class="col-md-12">
			<% if current_user.devices.any? %>
				<%= render partial: "table", object: @devices %>
			<% else %>
				<h3>No tienes equipos asignados.</h3>
				<p class="lead"><%= link_to 'Ver inventario', devices_path, class: "btn btn-primary btn-lg" %>

			<% end %>
		</div>
	</div>
<% else %>

	<div class="jumbotron">
		<div class="container">
			<h1>Inventario de calibraciones</h1>
			<p>Administra las calibraciones de tus equipos.</p>
			<div class="col-md-4">
				<p><%= link_to 'Regístrate', new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
			</div>
			<div class="col-md-4">
				<p><%= link_to 'Iniciar Sesión', new_user_session_path, class: "btn btn-primary btn-lg" %></p>
			</div>
		</div>
	</div>
<% end %>